{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.0.jar",
          "url": "compiler-0.5.0.jar",
          "size": 95337,
          "sha512": "139920ea4bae28ee0a2d87ca8431230cbfc6af77bf70a2df4acbc009e5aa3d5e73b6888afbe2c36f3dcc4f81cd6062bfe1615bebb1fdc3b319eb7421dfe5d11f",
          "sha256": "9b28e8abf40230cb5301f05d8fdad6cf29704e34f4cb8e06628e7b7166f4bf3c",
          "sha1": "6971f54c231649ad2d3223828082950ee25419b5",
          "md5": "c4d29a1104678cc0099b4bef29aa363d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.0.jar",
          "url": "compiler-0.5.0.jar",
          "size": 95337,
          "sha512": "139920ea4bae28ee0a2d87ca8431230cbfc6af77bf70a2df4acbc009e5aa3d5e73b6888afbe2c36f3dcc4f81cd6062bfe1615bebb1fdc3b319eb7421dfe5d11f",
          "sha256": "9b28e8abf40230cb5301f05d8fdad6cf29704e34f4cb8e06628e7b7166f4bf3c",
          "sha1": "6971f54c231649ad2d3223828082950ee25419b5",
          "md5": "c4d29a1104678cc0099b4bef29aa363d"
        }
      ]
    }
  ]
}
