{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.0.jar",
          "url": "compiler-0.5.0.jar",
          "size": 95494,
          "sha512": "aab259fe7d76a89b474fffd54a8d4f1452234f223d4c80ad3271a3ba1edddea491e0517fe60f5dd874259992a02e040820be5c0ed3c66815fdbb09fa5da1294a",
          "sha256": "bf8dcc997e8a10bdc56c8137f1c366b5810c30fb8817a9a33c76a9dfbb8fe31d",
          "sha1": "69cc61a0d8fcd7adc654c53900f54099ec45fb41",
          "md5": "79674cccfd61d6de33d84bcb6c83d1d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.0.jar",
          "url": "compiler-0.5.0.jar",
          "size": 95494,
          "sha512": "aab259fe7d76a89b474fffd54a8d4f1452234f223d4c80ad3271a3ba1edddea491e0517fe60f5dd874259992a02e040820be5c0ed3c66815fdbb09fa5da1294a",
          "sha256": "bf8dcc997e8a10bdc56c8137f1c366b5810c30fb8817a9a33c76a9dfbb8fe31d",
          "sha1": "69cc61a0d8fcd7adc654c53900f54099ec45fb41",
          "md5": "79674cccfd61d6de33d84bcb6c83d1d4"
        }
      ]
    }
  ]
}
