{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.1.jar",
          "url": "compiler-0.5.1.jar",
          "size": 95420,
          "sha512": "d2338a89626b627887b095c56cdcc5ddeb08ed016f880cf1aba9d4a7b6cc7b1f58db66242de581db0f0a7e0e0393469037e22bcbedbe10cd3c37cd4c23e35acf",
          "sha256": "162f3d1b7934dd670a2c69d87868c7596f55df84cb075d15ae7668f4c195bf73",
          "sha1": "6a0ff65cb45ee07dd9212c6f8acc639bbf320322",
          "md5": "e1067e03e7d35f51e7c5d2fd71f9485c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.5.1.jar",
          "url": "compiler-0.5.1.jar",
          "size": 95420,
          "sha512": "d2338a89626b627887b095c56cdcc5ddeb08ed016f880cf1aba9d4a7b6cc7b1f58db66242de581db0f0a7e0e0393469037e22bcbedbe10cd3c37cd4c23e35acf",
          "sha256": "162f3d1b7934dd670a2c69d87868c7596f55df84cb075d15ae7668f4c195bf73",
          "sha1": "6a0ff65cb45ee07dd9212c6f8acc639bbf320322",
          "md5": "e1067e03e7d35f51e7c5d2fd71f9485c"
        }
      ]
    }
  ]
}
