{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sample-lib/0.3.0/sample-lib-0.3.0.module",
    "group": "com.glureau.k2pb",
    "module": "sample-lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-jvm-0.3.0.jar",
          "url": "sample-lib-jvm-0.3.0.jar",
          "size": 10837,
          "sha512": "5dc889bf9c4e5674986976e473fa40d2a5f35263e4cd19476290d1bbdbcc8aeacfe7fb771b59a1be86be4e9e5313af8d6e50c79063178a5651b3a47e160c39ae",
          "sha256": "4c1dc4b382497e2964993c38fe6f91035ed2a7d384ec7e5bece1e7e13826a559",
          "sha1": "aa99fb4697b8ba89fcc4cab0ed3b2bfbfdad7e2a",
          "md5": "c55425ae76d74314ed6fa3eaba5dba71"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-jvm-0.3.0.jar",
          "url": "sample-lib-jvm-0.3.0.jar",
          "size": 10837,
          "sha512": "5dc889bf9c4e5674986976e473fa40d2a5f35263e4cd19476290d1bbdbcc8aeacfe7fb771b59a1be86be4e9e5313af8d6e50c79063178a5651b3a47e160c39ae",
          "sha256": "4c1dc4b382497e2964993c38fe6f91035ed2a7d384ec7e5bece1e7e13826a559",
          "sha1": "aa99fb4697b8ba89fcc4cab0ed3b2bfbfdad7e2a",
          "md5": "c55425ae76d74314ed6fa3eaba5dba71"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sample-lib-jvm-0.3.0-sources.jar",
          "url": "sample-lib-jvm-0.3.0-sources.jar",
          "size": 1475,
          "sha512": "3202eefc2d286785ceef33445d51cb64759625e932fdf1576d89bb2ec419334687cfa27e21ed9610a131e72494c7c1837d9518c1033d9e1b0f9c341afd130eae",
          "sha256": "370dedb9da0cfa4768a6952e86880e4fa12224d634a307aea811d8bd805c4828",
          "sha1": "7017b5e16908a50140cc0f7d3c0dce63989fc010",
          "md5": "2d654bc9a451f7a92679bb86e3b2dc1c"
        }
      ]
    }
  ]
}
