{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "sample-lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-metadata-0.3.0.jar",
          "url": "sample-lib-0.3.0.jar",
          "size": 670,
          "sha512": "32d19854dc6c8b30f202858b2a0ad8556a98d67d2846e9bd29f144a382066d77f294fc283ad5c96f08de1a2da3147837cc0e7c01be8620e18af7cc927d138003",
          "sha256": "7c38b9ef25f865f0f4b017e198baea31dcf30158ca68fa22d274a3ea270e7734",
          "sha1": "52f958fc2a69baba23dfd1f3e64dfc4143d08ed4",
          "md5": "e17f682b7a3680d96e2ae8549ea70bac"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sample-lib-kotlin-0.3.0-sources.jar",
          "url": "sample-lib-0.3.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-lib-jvm/0.3.0/sample-lib-jvm-0.3.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-lib-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-lib-jvm/0.3.0/sample-lib-jvm-0.3.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-lib-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-lib-jvm/0.3.0/sample-lib-jvm-0.3.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-lib-jvm",
        "version": "0.3.0"
      }
    }
  ]
}
