// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataClassFromLib.proto

public final class DataClassFromLibOuterClass {
  private DataClassFromLibOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataClassFromLibOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataClassFromLib)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 myInt = 1;</code>
     * @return The myInt.
     */
    int getMyInt();
  }
  /**
   * Protobuf type {@code DataClassFromLib}
   */
  public static final class DataClassFromLib extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataClassFromLib)
      DataClassFromLibOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataClassFromLib.newBuilder() to construct.
    private DataClassFromLib(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataClassFromLib() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataClassFromLib();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataClassFromLibOuterClass.internal_static_DataClassFromLib_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataClassFromLibOuterClass.internal_static_DataClassFromLib_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataClassFromLibOuterClass.DataClassFromLib.class, DataClassFromLibOuterClass.DataClassFromLib.Builder.class);
    }

    public static final int MYINT_FIELD_NUMBER = 1;
    private int myInt_ = 0;
    /**
     * <code>int32 myInt = 1;</code>
     * @return The myInt.
     */
    @java.lang.Override
    public int getMyInt() {
      return myInt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (myInt_ != 0) {
        output.writeInt32(1, myInt_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (myInt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, myInt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataClassFromLibOuterClass.DataClassFromLib)) {
        return super.equals(obj);
      }
      DataClassFromLibOuterClass.DataClassFromLib other = (DataClassFromLibOuterClass.DataClassFromLib) obj;

      if (getMyInt()
          != other.getMyInt()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MYINT_FIELD_NUMBER;
      hash = (53 * hash) + getMyInt();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static DataClassFromLibOuterClass.DataClassFromLib parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static DataClassFromLibOuterClass.DataClassFromLib parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataClassFromLibOuterClass.DataClassFromLib parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataClassFromLibOuterClass.DataClassFromLib prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataClassFromLib}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataClassFromLib)
        DataClassFromLibOuterClass.DataClassFromLibOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataClassFromLibOuterClass.internal_static_DataClassFromLib_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataClassFromLibOuterClass.internal_static_DataClassFromLib_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataClassFromLibOuterClass.DataClassFromLib.class, DataClassFromLibOuterClass.DataClassFromLib.Builder.class);
      }

      // Construct using DataClassFromLibOuterClass.DataClassFromLib.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        myInt_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataClassFromLibOuterClass.internal_static_DataClassFromLib_descriptor;
      }

      @java.lang.Override
      public DataClassFromLibOuterClass.DataClassFromLib getDefaultInstanceForType() {
        return DataClassFromLibOuterClass.DataClassFromLib.getDefaultInstance();
      }

      @java.lang.Override
      public DataClassFromLibOuterClass.DataClassFromLib build() {
        DataClassFromLibOuterClass.DataClassFromLib result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DataClassFromLibOuterClass.DataClassFromLib buildPartial() {
        DataClassFromLibOuterClass.DataClassFromLib result = new DataClassFromLibOuterClass.DataClassFromLib(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DataClassFromLibOuterClass.DataClassFromLib result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.myInt_ = myInt_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataClassFromLibOuterClass.DataClassFromLib) {
          return mergeFrom((DataClassFromLibOuterClass.DataClassFromLib)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataClassFromLibOuterClass.DataClassFromLib other) {
        if (other == DataClassFromLibOuterClass.DataClassFromLib.getDefaultInstance()) return this;
        if (other.getMyInt() != 0) {
          setMyInt(other.getMyInt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                myInt_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int myInt_ ;
      /**
       * <code>int32 myInt = 1;</code>
       * @return The myInt.
       */
      @java.lang.Override
      public int getMyInt() {
        return myInt_;
      }
      /**
       * <code>int32 myInt = 1;</code>
       * @param value The myInt to set.
       * @return This builder for chaining.
       */
      public Builder setMyInt(int value) {

        myInt_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 myInt = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyInt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        myInt_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataClassFromLib)
    }

    // @@protoc_insertion_point(class_scope:DataClassFromLib)
    private static final DataClassFromLibOuterClass.DataClassFromLib DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataClassFromLibOuterClass.DataClassFromLib();
    }

    public static DataClassFromLibOuterClass.DataClassFromLib getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataClassFromLib>
        PARSER = new com.google.protobuf.AbstractParser<DataClassFromLib>() {
      @java.lang.Override
      public DataClassFromLib parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataClassFromLib> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataClassFromLib> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DataClassFromLibOuterClass.DataClassFromLib getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataClassFromLib_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataClassFromLib_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026DataClassFromLib.proto\"!\n\020DataClassFro" +
      "mLib\022\r\n\005myInt\030\001 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataClassFromLib_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataClassFromLib_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataClassFromLib_descriptor,
        new java.lang.String[] { "MyInt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
