{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sample-app/0.1.0/sample-app-0.1.0.module",
    "group": "com.glureau.k2pb",
    "module": "sample-app",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sample-app-jvm-0.1.0.jar",
          "url": "sample-app-jvm-0.1.0.jar",
          "size": 144808,
          "sha512": "43a529401bbc8f23ca376c26a7e94221d88530fb32bf3dc3ec38ec8a467b2199c63e9433611242e03c290029f57dfa27ecf1e2ff5031e08de505c386d3f87999",
          "sha256": "44ab4af478e3d6632ba63649250725e352dce52cb8ea6a85b25430ff340e81da",
          "sha1": "23599720cf92cc9c7a8fa21e78627b860e77a8db",
          "md5": "f5ac0d91e7914ec5c5470863ef150327"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.glureau.k2pb",
          "module": "sample-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sample-app-jvm-0.1.0.jar",
          "url": "sample-app-jvm-0.1.0.jar",
          "size": 144808,
          "sha512": "43a529401bbc8f23ca376c26a7e94221d88530fb32bf3dc3ec38ec8a467b2199c63e9433611242e03c290029f57dfa27ecf1e2ff5031e08de505c386d3f87999",
          "sha256": "44ab4af478e3d6632ba63649250725e352dce52cb8ea6a85b25430ff340e81da",
          "sha1": "23599720cf92cc9c7a8fa21e78627b860e77a8db",
          "md5": "f5ac0d91e7914ec5c5470863ef150327"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sample-app-jvm-0.1.0-sources.jar",
          "url": "sample-app-jvm-0.1.0-sources.jar",
          "size": 6455,
          "sha512": "53ad3bc9ad3ec2f72c005b5d4c0c6e5bd4b3d30123239242e1325fea6c7384e52bd6e6b7be0ea6277af96fe88b519cf6b02b8738028efbc838ab11a0ec550704",
          "sha256": "c270dafbc06b19e6e4b76b51161d6af7b3371b00f18967ba921a82f656eb5fdf",
          "sha1": "0c1e18abdce106b9eb058f9d91ce34cf6bd035c9",
          "md5": "85cf377e13eeeba2224109e66b6b337d"
        }
      ]
    }
  ]
}
