// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: CommonClass.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializecommonClass")
public inline fun commonClass(block: CommonClassKt.Dsl.() -> kotlin.Unit): CommonClassOuterClass.CommonClass =
  CommonClassKt.Dsl._create(CommonClassOuterClass.CommonClass.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `CommonClass`
 */
public object CommonClassKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: CommonClassOuterClass.CommonClass.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: CommonClassOuterClass.CommonClass.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): CommonClassOuterClass.CommonClass = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun CommonClassOuterClass.CommonClass.copy(block: CommonClassKt.Dsl.() -> kotlin.Unit): CommonClassOuterClass.CommonClass =
  CommonClassKt.Dsl._create(this.toBuilder()).apply { block() }._build()

