package com.glureau.k2pb.gradle

open class K2PBExtension {
    /**
     * Change the package for all protobuf files generated.
      */
    var protoPackageName: String? = null

    /**
     * Change the package for all java files generated.
     * Using "option java_package", see https://protobuf.dev/programming-guides/proto3/#options
     * Keep it null to use the [protoPackageName] by default.
     */
    var javaPackage: String? = null
    /**
     * Change the suffix of outer class generated by protoc (by default using file name).
     * Using "option java_outer_classname", see https://protobuf.dev/programming-guides/proto3/#options
     * Keep it null to use the standard "OuterClass" suffix.
     */
    var javaOuterClassnameSuffix: String? = null

    /**
     * K2PB explicit nullability is using a specific enum to ensure a good support.
     * By default, a multi-module setup will emit multiple times this file, this setting
     * allow to disable the emission of this protobuf file.
     */
    var emitNullability: Boolean = true
}