{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 93742,
          "sha512": "c544cae8bab825a72920a0c5cae031ae90f1153af8e77e12c004cf6cebdbda5f2a769c48a63a91d876996c4ab15f9a6cce2e3f18b7f0187a68b7060858db599c",
          "sha256": "2d0bd6a8dda97519d99b89a55055970b4fbbd9b71eaa0749fb2f9802d190b9c3",
          "sha1": "2e9eb6c877d1a4b964aea1ddc08bf37dc592b11a",
          "md5": "e446ac27c5f5ecd0d050da181216bf16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 93742,
          "sha512": "c544cae8bab825a72920a0c5cae031ae90f1153af8e77e12c004cf6cebdbda5f2a769c48a63a91d876996c4ab15f9a6cce2e3f18b7f0187a68b7060858db599c",
          "sha256": "2d0bd6a8dda97519d99b89a55055970b4fbbd9b71eaa0749fb2f9802d190b9c3",
          "sha1": "2e9eb6c877d1a4b964aea1ddc08bf37dc592b11a",
          "md5": "e446ac27c5f5ecd0d050da181216bf16"
        }
      ]
    }
  ]
}
