{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 92387,
          "sha512": "15f2438983e39a363fd3367b1ff15bd1c4002e5003b903e0fd3c7706098bdc2b25d8d725a971c415d98d09ae72273be3f0e0e0483df60de1483fd9b3140bbd85",
          "sha256": "c76c3e77a91c9eefd5786e71a63f6089e31ebb7505a5b6b0eb71ec0b67d6ebfd",
          "sha1": "3059404a61de86236a7bc77350652f432798406e",
          "md5": "5fd896512b095a0b8bca5e2f1541b52b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.0.jar",
          "url": "compiler-0.3.0.jar",
          "size": 92387,
          "sha512": "15f2438983e39a363fd3367b1ff15bd1c4002e5003b903e0fd3c7706098bdc2b25d8d725a971c415d98d09ae72273be3f0e0e0483df60de1483fd9b3140bbd85",
          "sha256": "c76c3e77a91c9eefd5786e71a63f6089e31ebb7505a5b6b0eb71ec0b67d6ebfd",
          "sha1": "3059404a61de86236a7bc77350652f432798406e",
          "md5": "5fd896512b095a0b8bca5e2f1541b52b"
        }
      ]
    }
  ]
}
