{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "compiler",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.0.jar",
          "url": "compiler-0.4.0.jar",
          "size": 95406,
          "sha512": "66a9074f65d18510dca766f5debfb08e3a418c23386aaa8be6c93c1fe168931f5494be1b4ac108a10a5d1e27beef97e37619d55dfa8d18258f0affcb5a0a227e",
          "sha256": "4e53c3ec3a13ec0343e1c0a103fda3af4c05566ac124940844aba317a871fc44",
          "sha1": "89cbb4bab4e5db37254529569449846a145b024f",
          "md5": "5eef3956f4d8fe1b7ebd3fa8f7ff8f19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.25-1.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.0.jar",
          "url": "compiler-0.4.0.jar",
          "size": 95406,
          "sha512": "66a9074f65d18510dca766f5debfb08e3a418c23386aaa8be6c93c1fe168931f5494be1b4ac108a10a5d1e27beef97e37619d55dfa8d18258f0affcb5a0a227e",
          "sha256": "4e53c3ec3a13ec0343e1c0a103fda3af4c05566ac124940844aba317a871fc44",
          "sha1": "89cbb4bab4e5db37254529569449846a145b024f",
          "md5": "5eef3956f4d8fe1b7ebd3fa8f7ff8f19"
        }
      ]
    }
  ]
}
