{
  "formatVersion": "1.1",
  "component": {
    "group": "com.glureau.k2pb",
    "module": "sample-app",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sample-app-metadata-0.1.0.jar",
          "url": "sample-app-0.1.0.jar",
          "size": 674,
          "sha512": "32dd175b986a604d9742411729f85ae1d4254ed0826ffc9b990668091a3ef21eb5861a2eb1791cbed073ea9e180d91cc8516e0b07b8caeb4dc7f5a57f5458ef6",
          "sha256": "99b0762540e4e9460c840b6a08e5b781bbef0f3679d9a5403cee26b87bc4510a",
          "sha1": "c074d956789fe5a7dbf386b9ddb7e34d1618dbab",
          "md5": "03f2975eb3804acca2633715c8bcb518"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sample-app-kotlin-0.1.0-sources.jar",
          "url": "sample-app-0.1.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-app-jvm/0.1.0/sample-app-jvm-0.1.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-app-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-app-jvm/0.1.0/sample-app-jvm-0.1.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-app-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sample-app-jvm/0.1.0/sample-app-jvm-0.1.0.module",
        "group": "com.glureau.k2pb",
        "module": "sample-app-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
