// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BarEvent.proto

public final class BarEventOuterClass {
  private BarEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BarEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BarEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CommonClass common = 1;</code>
     * @return Whether the common field is set.
     */
    boolean hasCommon();
    /**
     * <code>.CommonClass common = 1;</code>
     * @return The common.
     */
    CommonClassOuterClass.CommonClass getCommon();
    /**
     * <code>.CommonClass common = 1;</code>
     */
    CommonClassOuterClass.CommonClassOrBuilder getCommonOrBuilder();
  }
  /**
   * Protobuf type {@code BarEvent}
   */
  public static final class BarEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BarEvent)
      BarEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BarEvent.newBuilder() to construct.
    private BarEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BarEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BarEvent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BarEventOuterClass.internal_static_BarEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BarEventOuterClass.internal_static_BarEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BarEventOuterClass.BarEvent.class, BarEventOuterClass.BarEvent.Builder.class);
    }

    public static final int COMMON_FIELD_NUMBER = 1;
    private CommonClassOuterClass.CommonClass common_;
    /**
     * <code>.CommonClass common = 1;</code>
     * @return Whether the common field is set.
     */
    @java.lang.Override
    public boolean hasCommon() {
      return common_ != null;
    }
    /**
     * <code>.CommonClass common = 1;</code>
     * @return The common.
     */
    @java.lang.Override
    public CommonClassOuterClass.CommonClass getCommon() {
      return common_ == null ? CommonClassOuterClass.CommonClass.getDefaultInstance() : common_;
    }
    /**
     * <code>.CommonClass common = 1;</code>
     */
    @java.lang.Override
    public CommonClassOuterClass.CommonClassOrBuilder getCommonOrBuilder() {
      return common_ == null ? CommonClassOuterClass.CommonClass.getDefaultInstance() : common_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (common_ != null) {
        output.writeMessage(1, getCommon());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (common_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BarEventOuterClass.BarEvent)) {
        return super.equals(obj);
      }
      BarEventOuterClass.BarEvent other = (BarEventOuterClass.BarEvent) obj;

      if (hasCommon() != other.hasCommon()) return false;
      if (hasCommon()) {
        if (!getCommon()
            .equals(other.getCommon())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommon()) {
        hash = (37 * hash) + COMMON_FIELD_NUMBER;
        hash = (53 * hash) + getCommon().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BarEventOuterClass.BarEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BarEventOuterClass.BarEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BarEventOuterClass.BarEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BarEventOuterClass.BarEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static BarEventOuterClass.BarEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BarEventOuterClass.BarEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BarEventOuterClass.BarEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BarEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BarEvent)
        BarEventOuterClass.BarEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BarEventOuterClass.internal_static_BarEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BarEventOuterClass.internal_static_BarEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BarEventOuterClass.BarEvent.class, BarEventOuterClass.BarEvent.Builder.class);
      }

      // Construct using BarEventOuterClass.BarEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        common_ = null;
        if (commonBuilder_ != null) {
          commonBuilder_.dispose();
          commonBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BarEventOuterClass.internal_static_BarEvent_descriptor;
      }

      @java.lang.Override
      public BarEventOuterClass.BarEvent getDefaultInstanceForType() {
        return BarEventOuterClass.BarEvent.getDefaultInstance();
      }

      @java.lang.Override
      public BarEventOuterClass.BarEvent build() {
        BarEventOuterClass.BarEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BarEventOuterClass.BarEvent buildPartial() {
        BarEventOuterClass.BarEvent result = new BarEventOuterClass.BarEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(BarEventOuterClass.BarEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.common_ = commonBuilder_ == null
              ? common_
              : commonBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BarEventOuterClass.BarEvent) {
          return mergeFrom((BarEventOuterClass.BarEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BarEventOuterClass.BarEvent other) {
        if (other == BarEventOuterClass.BarEvent.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCommonFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private CommonClassOuterClass.CommonClass common_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonClassOuterClass.CommonClass, CommonClassOuterClass.CommonClass.Builder, CommonClassOuterClass.CommonClassOrBuilder> commonBuilder_;
      /**
       * <code>.CommonClass common = 1;</code>
       * @return Whether the common field is set.
       */
      public boolean hasCommon() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.CommonClass common = 1;</code>
       * @return The common.
       */
      public CommonClassOuterClass.CommonClass getCommon() {
        if (commonBuilder_ == null) {
          return common_ == null ? CommonClassOuterClass.CommonClass.getDefaultInstance() : common_;
        } else {
          return commonBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public Builder setCommon(CommonClassOuterClass.CommonClass value) {
        if (commonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          common_ = value;
        } else {
          commonBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public Builder setCommon(
          CommonClassOuterClass.CommonClass.Builder builderForValue) {
        if (commonBuilder_ == null) {
          common_ = builderForValue.build();
        } else {
          commonBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public Builder mergeCommon(CommonClassOuterClass.CommonClass value) {
        if (commonBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            common_ != null &&
            common_ != CommonClassOuterClass.CommonClass.getDefaultInstance()) {
            getCommonBuilder().mergeFrom(value);
          } else {
            common_ = value;
          }
        } else {
          commonBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public Builder clearCommon() {
        bitField0_ = (bitField0_ & ~0x00000001);
        common_ = null;
        if (commonBuilder_ != null) {
          commonBuilder_.dispose();
          commonBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public CommonClassOuterClass.CommonClass.Builder getCommonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCommonFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      public CommonClassOuterClass.CommonClassOrBuilder getCommonOrBuilder() {
        if (commonBuilder_ != null) {
          return commonBuilder_.getMessageOrBuilder();
        } else {
          return common_ == null ?
              CommonClassOuterClass.CommonClass.getDefaultInstance() : common_;
        }
      }
      /**
       * <code>.CommonClass common = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonClassOuterClass.CommonClass, CommonClassOuterClass.CommonClass.Builder, CommonClassOuterClass.CommonClassOrBuilder> 
          getCommonFieldBuilder() {
        if (commonBuilder_ == null) {
          commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonClassOuterClass.CommonClass, CommonClassOuterClass.CommonClass.Builder, CommonClassOuterClass.CommonClassOrBuilder>(
                  getCommon(),
                  getParentForChildren(),
                  isClean());
          common_ = null;
        }
        return commonBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BarEvent)
    }

    // @@protoc_insertion_point(class_scope:BarEvent)
    private static final BarEventOuterClass.BarEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BarEventOuterClass.BarEvent();
    }

    public static BarEventOuterClass.BarEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BarEvent>
        PARSER = new com.google.protobuf.AbstractParser<BarEvent>() {
      @java.lang.Override
      public BarEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BarEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BarEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BarEventOuterClass.BarEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BarEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BarEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016BarEvent.proto\032\021CommonClass.proto\"(\n\010B" +
      "arEvent\022\034\n\006common\030\001 \001(\0132\014.CommonClassb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonClassOuterClass.getDescriptor(),
        });
    internal_static_BarEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BarEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BarEvent_descriptor,
        new java.lang.String[] { "Common", });
    CommonClassOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
