// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommentedClass.proto

public final class CommentedClassOuterClass {
  private CommentedClassOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentedClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommentedClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *
     *This field has kdoc comment.
     * </pre>
     *
     * <code>string fieldWithComment = 1;</code>
     * @return The fieldWithComment.
     */
    java.lang.String getFieldWithComment();
    /**
     * <pre>
     *
     *This field has kdoc comment.
     * </pre>
     *
     * <code>string fieldWithComment = 1;</code>
     * @return The bytes for fieldWithComment.
     */
    com.google.protobuf.ByteString
        getFieldWithCommentBytes();
  }
  /**
   * <pre>
   *
   *This class has kdoc comment.
   * </pre>
   *
   * Protobuf type {@code CommentedClass}
   */
  public static final class CommentedClass extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommentedClass)
      CommentedClassOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommentedClass.newBuilder() to construct.
    private CommentedClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommentedClass() {
      fieldWithComment_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommentedClass();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommentedClassOuterClass.internal_static_CommentedClass_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommentedClassOuterClass.internal_static_CommentedClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommentedClassOuterClass.CommentedClass.class, CommentedClassOuterClass.CommentedClass.Builder.class);
    }

    public static final int FIELDWITHCOMMENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fieldWithComment_ = "";
    /**
     * <pre>
     *
     *This field has kdoc comment.
     * </pre>
     *
     * <code>string fieldWithComment = 1;</code>
     * @return The fieldWithComment.
     */
    @java.lang.Override
    public java.lang.String getFieldWithComment() {
      java.lang.Object ref = fieldWithComment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldWithComment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     *This field has kdoc comment.
     * </pre>
     *
     * <code>string fieldWithComment = 1;</code>
     * @return The bytes for fieldWithComment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldWithCommentBytes() {
      java.lang.Object ref = fieldWithComment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldWithComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fieldWithComment_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldWithComment_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fieldWithComment_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldWithComment_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommentedClassOuterClass.CommentedClass)) {
        return super.equals(obj);
      }
      CommentedClassOuterClass.CommentedClass other = (CommentedClassOuterClass.CommentedClass) obj;

      if (!getFieldWithComment()
          .equals(other.getFieldWithComment())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELDWITHCOMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getFieldWithComment().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommentedClassOuterClass.CommentedClass parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CommentedClassOuterClass.CommentedClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CommentedClassOuterClass.CommentedClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommentedClassOuterClass.CommentedClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommentedClassOuterClass.CommentedClass prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *
     *This class has kdoc comment.
     * </pre>
     *
     * Protobuf type {@code CommentedClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommentedClass)
        CommentedClassOuterClass.CommentedClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommentedClassOuterClass.internal_static_CommentedClass_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommentedClassOuterClass.internal_static_CommentedClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommentedClassOuterClass.CommentedClass.class, CommentedClassOuterClass.CommentedClass.Builder.class);
      }

      // Construct using CommentedClassOuterClass.CommentedClass.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fieldWithComment_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommentedClassOuterClass.internal_static_CommentedClass_descriptor;
      }

      @java.lang.Override
      public CommentedClassOuterClass.CommentedClass getDefaultInstanceForType() {
        return CommentedClassOuterClass.CommentedClass.getDefaultInstance();
      }

      @java.lang.Override
      public CommentedClassOuterClass.CommentedClass build() {
        CommentedClassOuterClass.CommentedClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CommentedClassOuterClass.CommentedClass buildPartial() {
        CommentedClassOuterClass.CommentedClass result = new CommentedClassOuterClass.CommentedClass(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CommentedClassOuterClass.CommentedClass result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fieldWithComment_ = fieldWithComment_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommentedClassOuterClass.CommentedClass) {
          return mergeFrom((CommentedClassOuterClass.CommentedClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommentedClassOuterClass.CommentedClass other) {
        if (other == CommentedClassOuterClass.CommentedClass.getDefaultInstance()) return this;
        if (!other.getFieldWithComment().isEmpty()) {
          fieldWithComment_ = other.fieldWithComment_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fieldWithComment_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fieldWithComment_ = "";
      /**
       * <pre>
       *
       *This field has kdoc comment.
       * </pre>
       *
       * <code>string fieldWithComment = 1;</code>
       * @return The fieldWithComment.
       */
      public java.lang.String getFieldWithComment() {
        java.lang.Object ref = fieldWithComment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldWithComment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *
       *This field has kdoc comment.
       * </pre>
       *
       * <code>string fieldWithComment = 1;</code>
       * @return The bytes for fieldWithComment.
       */
      public com.google.protobuf.ByteString
          getFieldWithCommentBytes() {
        java.lang.Object ref = fieldWithComment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldWithComment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       *This field has kdoc comment.
       * </pre>
       *
       * <code>string fieldWithComment = 1;</code>
       * @param value The fieldWithComment to set.
       * @return This builder for chaining.
       */
      public Builder setFieldWithComment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fieldWithComment_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       *This field has kdoc comment.
       * </pre>
       *
       * <code>string fieldWithComment = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldWithComment() {
        fieldWithComment_ = getDefaultInstance().getFieldWithComment();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       *This field has kdoc comment.
       * </pre>
       *
       * <code>string fieldWithComment = 1;</code>
       * @param value The bytes for fieldWithComment to set.
       * @return This builder for chaining.
       */
      public Builder setFieldWithCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fieldWithComment_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommentedClass)
    }

    // @@protoc_insertion_point(class_scope:CommentedClass)
    private static final CommentedClassOuterClass.CommentedClass DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommentedClassOuterClass.CommentedClass();
    }

    public static CommentedClassOuterClass.CommentedClass getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommentedClass>
        PARSER = new com.google.protobuf.AbstractParser<CommentedClass>() {
      @java.lang.Override
      public CommentedClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommentedClass> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommentedClass> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CommentedClassOuterClass.CommentedClass getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentedClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentedClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024CommentedClass.proto\"*\n\016CommentedClass" +
      "\022\030\n\020fieldWithComment\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CommentedClass_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommentedClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentedClass_descriptor,
        new java.lang.String[] { "FieldWithComment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
