// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NativeTypeEvent.proto

public final class NativeTypeEventOuterClass {
  private NativeTypeEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NativeTypeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NativeTypeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 integer = 1;</code>
     * @return The integer.
     */
    int getInteger();

    /**
     * <code>int64 long = 2;</code>
     * @return The long.
     */
    long getLong();

    /**
     * <code>float float = 3;</code>
     * @return The float.
     */
    float getFloat();

    /**
     * <code>double double = 4;</code>
     * @return The double.
     */
    double getDouble();

    /**
     * <code>string string = 5;</code>
     * @return The string.
     */
    java.lang.String getString();
    /**
     * <code>string string = 5;</code>
     * @return The bytes for string.
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>int32 short = 6;</code>
     * @return The short.
     */
    int getShort();

    /**
     * <code>int32 char = 7;</code>
     * @return The char.
     */
    int getChar();

    /**
     * <code>bool boolean = 8;</code>
     * @return The boolean.
     */
    boolean getBoolean();

    /**
     * <code>int32 byte = 9;</code>
     * @return The byte.
     */
    int getByte();
  }
  /**
   * Protobuf type {@code NativeTypeEvent}
   */
  public static final class NativeTypeEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NativeTypeEvent)
      NativeTypeEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NativeTypeEvent.newBuilder() to construct.
    private NativeTypeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NativeTypeEvent() {
      string_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NativeTypeEvent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NativeTypeEventOuterClass.internal_static_NativeTypeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NativeTypeEventOuterClass.internal_static_NativeTypeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NativeTypeEventOuterClass.NativeTypeEvent.class, NativeTypeEventOuterClass.NativeTypeEvent.Builder.class);
    }

    public static final int INTEGER_FIELD_NUMBER = 1;
    private int integer_ = 0;
    /**
     * <code>int32 integer = 1;</code>
     * @return The integer.
     */
    @java.lang.Override
    public int getInteger() {
      return integer_;
    }

    public static final int LONG_FIELD_NUMBER = 2;
    private long long_ = 0L;
    /**
     * <code>int64 long = 2;</code>
     * @return The long.
     */
    @java.lang.Override
    public long getLong() {
      return long_;
    }

    public static final int FLOAT_FIELD_NUMBER = 3;
    private float float_ = 0F;
    /**
     * <code>float float = 3;</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      return float_;
    }

    public static final int DOUBLE_FIELD_NUMBER = 4;
    private double double_ = 0D;
    /**
     * <code>double double = 4;</code>
     * @return The double.
     */
    @java.lang.Override
    public double getDouble() {
      return double_;
    }

    public static final int STRING_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object string_ = "";
    /**
     * <code>string string = 5;</code>
     * @return The string.
     */
    @java.lang.Override
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      }
    }
    /**
     * <code>string string = 5;</code>
     * @return The bytes for string.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORT_FIELD_NUMBER = 6;
    private int short_ = 0;
    /**
     * <code>int32 short = 6;</code>
     * @return The short.
     */
    @java.lang.Override
    public int getShort() {
      return short_;
    }

    public static final int CHAR_FIELD_NUMBER = 7;
    private int char_ = 0;
    /**
     * <code>int32 char = 7;</code>
     * @return The char.
     */
    @java.lang.Override
    public int getChar() {
      return char_;
    }

    public static final int BOOLEAN_FIELD_NUMBER = 8;
    private boolean boolean_ = false;
    /**
     * <code>bool boolean = 8;</code>
     * @return The boolean.
     */
    @java.lang.Override
    public boolean getBoolean() {
      return boolean_;
    }

    public static final int BYTE_FIELD_NUMBER = 9;
    private int byte_ = 0;
    /**
     * <code>int32 byte = 9;</code>
     * @return The byte.
     */
    @java.lang.Override
    public int getByte() {
      return byte_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (integer_ != 0) {
        output.writeInt32(1, integer_);
      }
      if (long_ != 0L) {
        output.writeInt64(2, long_);
      }
      if (java.lang.Float.floatToRawIntBits(float_) != 0) {
        output.writeFloat(3, float_);
      }
      if (java.lang.Double.doubleToRawLongBits(double_) != 0) {
        output.writeDouble(4, double_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, string_);
      }
      if (short_ != 0) {
        output.writeInt32(6, short_);
      }
      if (char_ != 0) {
        output.writeInt32(7, char_);
      }
      if (boolean_ != false) {
        output.writeBool(8, boolean_);
      }
      if (byte_ != 0) {
        output.writeInt32(9, byte_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (integer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, integer_);
      }
      if (long_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, long_);
      }
      if (java.lang.Float.floatToRawIntBits(float_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, float_);
      }
      if (java.lang.Double.doubleToRawLongBits(double_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, double_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, string_);
      }
      if (short_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, short_);
      }
      if (char_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, char_);
      }
      if (boolean_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, boolean_);
      }
      if (byte_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, byte_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NativeTypeEventOuterClass.NativeTypeEvent)) {
        return super.equals(obj);
      }
      NativeTypeEventOuterClass.NativeTypeEvent other = (NativeTypeEventOuterClass.NativeTypeEvent) obj;

      if (getInteger()
          != other.getInteger()) return false;
      if (getLong()
          != other.getLong()) return false;
      if (java.lang.Float.floatToIntBits(getFloat())
          != java.lang.Float.floatToIntBits(
              other.getFloat())) return false;
      if (java.lang.Double.doubleToLongBits(getDouble())
          != java.lang.Double.doubleToLongBits(
              other.getDouble())) return false;
      if (!getString()
          .equals(other.getString())) return false;
      if (getShort()
          != other.getShort()) return false;
      if (getChar()
          != other.getChar()) return false;
      if (getBoolean()
          != other.getBoolean()) return false;
      if (getByte()
          != other.getByte()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTEGER_FIELD_NUMBER;
      hash = (53 * hash) + getInteger();
      hash = (37 * hash) + LONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLong());
      hash = (37 * hash) + FLOAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFloat());
      hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDouble()));
      hash = (37 * hash) + STRING_FIELD_NUMBER;
      hash = (53 * hash) + getString().hashCode();
      hash = (37 * hash) + SHORT_FIELD_NUMBER;
      hash = (53 * hash) + getShort();
      hash = (37 * hash) + CHAR_FIELD_NUMBER;
      hash = (53 * hash) + getChar();
      hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolean());
      hash = (37 * hash) + BYTE_FIELD_NUMBER;
      hash = (53 * hash) + getByte();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NativeTypeEventOuterClass.NativeTypeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NativeTypeEventOuterClass.NativeTypeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NativeTypeEventOuterClass.NativeTypeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NativeTypeEventOuterClass.NativeTypeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NativeTypeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NativeTypeEvent)
        NativeTypeEventOuterClass.NativeTypeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NativeTypeEventOuterClass.internal_static_NativeTypeEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NativeTypeEventOuterClass.internal_static_NativeTypeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NativeTypeEventOuterClass.NativeTypeEvent.class, NativeTypeEventOuterClass.NativeTypeEvent.Builder.class);
      }

      // Construct using NativeTypeEventOuterClass.NativeTypeEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        integer_ = 0;
        long_ = 0L;
        float_ = 0F;
        double_ = 0D;
        string_ = "";
        short_ = 0;
        char_ = 0;
        boolean_ = false;
        byte_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NativeTypeEventOuterClass.internal_static_NativeTypeEvent_descriptor;
      }

      @java.lang.Override
      public NativeTypeEventOuterClass.NativeTypeEvent getDefaultInstanceForType() {
        return NativeTypeEventOuterClass.NativeTypeEvent.getDefaultInstance();
      }

      @java.lang.Override
      public NativeTypeEventOuterClass.NativeTypeEvent build() {
        NativeTypeEventOuterClass.NativeTypeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NativeTypeEventOuterClass.NativeTypeEvent buildPartial() {
        NativeTypeEventOuterClass.NativeTypeEvent result = new NativeTypeEventOuterClass.NativeTypeEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(NativeTypeEventOuterClass.NativeTypeEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.integer_ = integer_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.long_ = long_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.float_ = float_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.double_ = double_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.string_ = string_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.short_ = short_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.char_ = char_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.boolean_ = boolean_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.byte_ = byte_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NativeTypeEventOuterClass.NativeTypeEvent) {
          return mergeFrom((NativeTypeEventOuterClass.NativeTypeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NativeTypeEventOuterClass.NativeTypeEvent other) {
        if (other == NativeTypeEventOuterClass.NativeTypeEvent.getDefaultInstance()) return this;
        if (other.getInteger() != 0) {
          setInteger(other.getInteger());
        }
        if (other.getLong() != 0L) {
          setLong(other.getLong());
        }
        if (other.getFloat() != 0F) {
          setFloat(other.getFloat());
        }
        if (other.getDouble() != 0D) {
          setDouble(other.getDouble());
        }
        if (!other.getString().isEmpty()) {
          string_ = other.string_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getShort() != 0) {
          setShort(other.getShort());
        }
        if (other.getChar() != 0) {
          setChar(other.getChar());
        }
        if (other.getBoolean() != false) {
          setBoolean(other.getBoolean());
        }
        if (other.getByte() != 0) {
          setByte(other.getByte());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                integer_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                long_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 29: {
                float_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 33: {
                double_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 42: {
                string_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                short_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                char_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                boolean_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                byte_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int integer_ ;
      /**
       * <code>int32 integer = 1;</code>
       * @return The integer.
       */
      @java.lang.Override
      public int getInteger() {
        return integer_;
      }
      /**
       * <code>int32 integer = 1;</code>
       * @param value The integer to set.
       * @return This builder for chaining.
       */
      public Builder setInteger(int value) {

        integer_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 integer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInteger() {
        bitField0_ = (bitField0_ & ~0x00000001);
        integer_ = 0;
        onChanged();
        return this;
      }

      private long long_ ;
      /**
       * <code>int64 long = 2;</code>
       * @return The long.
       */
      @java.lang.Override
      public long getLong() {
        return long_;
      }
      /**
       * <code>int64 long = 2;</code>
       * @param value The long to set.
       * @return This builder for chaining.
       */
      public Builder setLong(long value) {

        long_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 long = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLong() {
        bitField0_ = (bitField0_ & ~0x00000002);
        long_ = 0L;
        onChanged();
        return this;
      }

      private float float_ ;
      /**
       * <code>float float = 3;</code>
       * @return The float.
       */
      @java.lang.Override
      public float getFloat() {
        return float_;
      }
      /**
       * <code>float float = 3;</code>
       * @param value The float to set.
       * @return This builder for chaining.
       */
      public Builder setFloat(float value) {

        float_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float float = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        float_ = 0F;
        onChanged();
        return this;
      }

      private double double_ ;
      /**
       * <code>double double = 4;</code>
       * @return The double.
       */
      @java.lang.Override
      public double getDouble() {
        return double_;
      }
      /**
       * <code>double double = 4;</code>
       * @param value The double to set.
       * @return This builder for chaining.
       */
      public Builder setDouble(double value) {

        double_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double double = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDouble() {
        bitField0_ = (bitField0_ & ~0x00000008);
        double_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object string_ = "";
      /**
       * <code>string string = 5;</code>
       * @return The string.
       */
      public java.lang.String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string = 5;</code>
       * @return The bytes for string.
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = string_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string = 5;</code>
       * @param value The string to set.
       * @return This builder for chaining.
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        string_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string string = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearString() {
        string_ = getDefaultInstance().getString();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string string = 5;</code>
       * @param value The bytes for string to set.
       * @return This builder for chaining.
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        string_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int short_ ;
      /**
       * <code>int32 short = 6;</code>
       * @return The short.
       */
      @java.lang.Override
      public int getShort() {
        return short_;
      }
      /**
       * <code>int32 short = 6;</code>
       * @param value The short to set.
       * @return This builder for chaining.
       */
      public Builder setShort(int value) {

        short_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 short = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearShort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        short_ = 0;
        onChanged();
        return this;
      }

      private int char_ ;
      /**
       * <code>int32 char = 7;</code>
       * @return The char.
       */
      @java.lang.Override
      public int getChar() {
        return char_;
      }
      /**
       * <code>int32 char = 7;</code>
       * @param value The char to set.
       * @return This builder for chaining.
       */
      public Builder setChar(int value) {

        char_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 char = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearChar() {
        bitField0_ = (bitField0_ & ~0x00000040);
        char_ = 0;
        onChanged();
        return this;
      }

      private boolean boolean_ ;
      /**
       * <code>bool boolean = 8;</code>
       * @return The boolean.
       */
      @java.lang.Override
      public boolean getBoolean() {
        return boolean_;
      }
      /**
       * <code>bool boolean = 8;</code>
       * @param value The boolean to set.
       * @return This builder for chaining.
       */
      public Builder setBoolean(boolean value) {

        boolean_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolean = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolean() {
        bitField0_ = (bitField0_ & ~0x00000080);
        boolean_ = false;
        onChanged();
        return this;
      }

      private int byte_ ;
      /**
       * <code>int32 byte = 9;</code>
       * @return The byte.
       */
      @java.lang.Override
      public int getByte() {
        return byte_;
      }
      /**
       * <code>int32 byte = 9;</code>
       * @param value The byte to set.
       * @return This builder for chaining.
       */
      public Builder setByte(int value) {

        byte_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 byte = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearByte() {
        bitField0_ = (bitField0_ & ~0x00000100);
        byte_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NativeTypeEvent)
    }

    // @@protoc_insertion_point(class_scope:NativeTypeEvent)
    private static final NativeTypeEventOuterClass.NativeTypeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NativeTypeEventOuterClass.NativeTypeEvent();
    }

    public static NativeTypeEventOuterClass.NativeTypeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NativeTypeEvent>
        PARSER = new com.google.protobuf.AbstractParser<NativeTypeEvent>() {
      @java.lang.Override
      public NativeTypeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NativeTypeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NativeTypeEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NativeTypeEventOuterClass.NativeTypeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NativeTypeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NativeTypeEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025NativeTypeEvent.proto\"\233\001\n\017NativeTypeEv" +
      "ent\022\017\n\007integer\030\001 \001(\005\022\014\n\004long\030\002 \001(\003\022\r\n\005fl" +
      "oat\030\003 \001(\002\022\016\n\006double\030\004 \001(\001\022\016\n\006string\030\005 \001(" +
      "\t\022\r\n\005short\030\006 \001(\005\022\014\n\004char\030\007 \001(\005\022\017\n\007boolea" +
      "n\030\010 \001(\010\022\014\n\004byte\030\t \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NativeTypeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NativeTypeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NativeTypeEvent_descriptor,
        new java.lang.String[] { "Integer", "Long", "Float", "Double", "String", "Short", "Char", "Boolean", "Byte", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
