// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     * @return Whether the bike field is set.
     */
    boolean hasBike();
    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     * @return The bike.
     */
    VehicleOuterClass.Vehicle.Bike getBike();
    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     */
    VehicleOuterClass.Vehicle.BikeOrBuilder getBikeOrBuilder();

    /**
     * <code>.Vehicle.Car Car = 3;</code>
     * @return Whether the car field is set.
     */
    boolean hasCar();
    /**
     * <code>.Vehicle.Car Car = 3;</code>
     * @return The car.
     */
    VehicleOuterClass.Vehicle.Car getCar();
    /**
     * <code>.Vehicle.Car Car = 3;</code>
     */
    VehicleOuterClass.Vehicle.CarOrBuilder getCarOrBuilder();

    UserOuterClass.User.VehicleCase getVehicleCase();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserOuterClass.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserOuterClass.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserOuterClass.User.class, UserOuterClass.User.Builder.class);
    }

    private int vehicleCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object vehicle_;
    public enum VehicleCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BIKE(2),
      CAR(3),
      VEHICLE_NOT_SET(0);
      private final int value;
      private VehicleCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VehicleCase valueOf(int value) {
        return forNumber(value);
      }

      public static VehicleCase forNumber(int value) {
        switch (value) {
          case 2: return BIKE;
          case 3: return CAR;
          case 0: return VEHICLE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public VehicleCase
    getVehicleCase() {
      return VehicleCase.forNumber(
          vehicleCase_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKE_FIELD_NUMBER = 2;
    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     * @return Whether the bike field is set.
     */
    @java.lang.Override
    public boolean hasBike() {
      return vehicleCase_ == 2;
    }
    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     * @return The bike.
     */
    @java.lang.Override
    public VehicleOuterClass.Vehicle.Bike getBike() {
      if (vehicleCase_ == 2) {
         return (VehicleOuterClass.Vehicle.Bike) vehicle_;
      }
      return VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
    }
    /**
     * <code>.Vehicle.Bike Bike = 2;</code>
     */
    @java.lang.Override
    public VehicleOuterClass.Vehicle.BikeOrBuilder getBikeOrBuilder() {
      if (vehicleCase_ == 2) {
         return (VehicleOuterClass.Vehicle.Bike) vehicle_;
      }
      return VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
    }

    public static final int CAR_FIELD_NUMBER = 3;
    /**
     * <code>.Vehicle.Car Car = 3;</code>
     * @return Whether the car field is set.
     */
    @java.lang.Override
    public boolean hasCar() {
      return vehicleCase_ == 3;
    }
    /**
     * <code>.Vehicle.Car Car = 3;</code>
     * @return The car.
     */
    @java.lang.Override
    public VehicleOuterClass.Vehicle.Car getCar() {
      if (vehicleCase_ == 3) {
         return (VehicleOuterClass.Vehicle.Car) vehicle_;
      }
      return VehicleOuterClass.Vehicle.Car.getDefaultInstance();
    }
    /**
     * <code>.Vehicle.Car Car = 3;</code>
     */
    @java.lang.Override
    public VehicleOuterClass.Vehicle.CarOrBuilder getCarOrBuilder() {
      if (vehicleCase_ == 3) {
         return (VehicleOuterClass.Vehicle.Car) vehicle_;
      }
      return VehicleOuterClass.Vehicle.Car.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (vehicleCase_ == 2) {
        output.writeMessage(2, (VehicleOuterClass.Vehicle.Bike) vehicle_);
      }
      if (vehicleCase_ == 3) {
        output.writeMessage(3, (VehicleOuterClass.Vehicle.Car) vehicle_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (vehicleCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (VehicleOuterClass.Vehicle.Bike) vehicle_);
      }
      if (vehicleCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (VehicleOuterClass.Vehicle.Car) vehicle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserOuterClass.User)) {
        return super.equals(obj);
      }
      UserOuterClass.User other = (UserOuterClass.User) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getVehicleCase().equals(other.getVehicleCase())) return false;
      switch (vehicleCase_) {
        case 2:
          if (!getBike()
              .equals(other.getBike())) return false;
          break;
        case 3:
          if (!getCar()
              .equals(other.getCar())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      switch (vehicleCase_) {
        case 2:
          hash = (37 * hash) + BIKE_FIELD_NUMBER;
          hash = (53 * hash) + getBike().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CAR_FIELD_NUMBER;
          hash = (53 * hash) + getCar().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserOuterClass.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserOuterClass.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserOuterClass.User.class, UserOuterClass.User.Builder.class);
      }

      // Construct using UserOuterClass.User.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        if (bikeBuilder_ != null) {
          bikeBuilder_.clear();
        }
        if (carBuilder_ != null) {
          carBuilder_.clear();
        }
        vehicleCase_ = 0;
        vehicle_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserOuterClass.internal_static_User_descriptor;
      }

      @java.lang.Override
      public UserOuterClass.User getDefaultInstanceForType() {
        return UserOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public UserOuterClass.User build() {
        UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserOuterClass.User buildPartial() {
        UserOuterClass.User result = new UserOuterClass.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(UserOuterClass.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
      }

      private void buildPartialOneofs(UserOuterClass.User result) {
        result.vehicleCase_ = vehicleCase_;
        result.vehicle_ = this.vehicle_;
        if (vehicleCase_ == 2 &&
            bikeBuilder_ != null) {
          result.vehicle_ = bikeBuilder_.build();
        }
        if (vehicleCase_ == 3 &&
            carBuilder_ != null) {
          result.vehicle_ = carBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserOuterClass.User) {
          return mergeFrom((UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserOuterClass.User other) {
        if (other == UserOuterClass.User.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        switch (other.getVehicleCase()) {
          case BIKE: {
            mergeBike(other.getBike());
            break;
          }
          case CAR: {
            mergeCar(other.getCar());
            break;
          }
          case VEHICLE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getBikeFieldBuilder().getBuilder(),
                    extensionRegistry);
                vehicleCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getCarFieldBuilder().getBuilder(),
                    extensionRegistry);
                vehicleCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int vehicleCase_ = 0;
      private java.lang.Object vehicle_;
      public VehicleCase
          getVehicleCase() {
        return VehicleCase.forNumber(
            vehicleCase_);
      }

      public Builder clearVehicle() {
        vehicleCase_ = 0;
        vehicle_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleOuterClass.Vehicle.Bike, VehicleOuterClass.Vehicle.Bike.Builder, VehicleOuterClass.Vehicle.BikeOrBuilder> bikeBuilder_;
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       * @return Whether the bike field is set.
       */
      @java.lang.Override
      public boolean hasBike() {
        return vehicleCase_ == 2;
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       * @return The bike.
       */
      @java.lang.Override
      public VehicleOuterClass.Vehicle.Bike getBike() {
        if (bikeBuilder_ == null) {
          if (vehicleCase_ == 2) {
            return (VehicleOuterClass.Vehicle.Bike) vehicle_;
          }
          return VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
        } else {
          if (vehicleCase_ == 2) {
            return bikeBuilder_.getMessage();
          }
          return VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
        }
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      public Builder setBike(VehicleOuterClass.Vehicle.Bike value) {
        if (bikeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vehicle_ = value;
          onChanged();
        } else {
          bikeBuilder_.setMessage(value);
        }
        vehicleCase_ = 2;
        return this;
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      public Builder setBike(
          VehicleOuterClass.Vehicle.Bike.Builder builderForValue) {
        if (bikeBuilder_ == null) {
          vehicle_ = builderForValue.build();
          onChanged();
        } else {
          bikeBuilder_.setMessage(builderForValue.build());
        }
        vehicleCase_ = 2;
        return this;
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      public Builder mergeBike(VehicleOuterClass.Vehicle.Bike value) {
        if (bikeBuilder_ == null) {
          if (vehicleCase_ == 2 &&
              vehicle_ != VehicleOuterClass.Vehicle.Bike.getDefaultInstance()) {
            vehicle_ = VehicleOuterClass.Vehicle.Bike.newBuilder((VehicleOuterClass.Vehicle.Bike) vehicle_)
                .mergeFrom(value).buildPartial();
          } else {
            vehicle_ = value;
          }
          onChanged();
        } else {
          if (vehicleCase_ == 2) {
            bikeBuilder_.mergeFrom(value);
          } else {
            bikeBuilder_.setMessage(value);
          }
        }
        vehicleCase_ = 2;
        return this;
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      public Builder clearBike() {
        if (bikeBuilder_ == null) {
          if (vehicleCase_ == 2) {
            vehicleCase_ = 0;
            vehicle_ = null;
            onChanged();
          }
        } else {
          if (vehicleCase_ == 2) {
            vehicleCase_ = 0;
            vehicle_ = null;
          }
          bikeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      public VehicleOuterClass.Vehicle.Bike.Builder getBikeBuilder() {
        return getBikeFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      @java.lang.Override
      public VehicleOuterClass.Vehicle.BikeOrBuilder getBikeOrBuilder() {
        if ((vehicleCase_ == 2) && (bikeBuilder_ != null)) {
          return bikeBuilder_.getMessageOrBuilder();
        } else {
          if (vehicleCase_ == 2) {
            return (VehicleOuterClass.Vehicle.Bike) vehicle_;
          }
          return VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
        }
      }
      /**
       * <code>.Vehicle.Bike Bike = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleOuterClass.Vehicle.Bike, VehicleOuterClass.Vehicle.Bike.Builder, VehicleOuterClass.Vehicle.BikeOrBuilder> 
          getBikeFieldBuilder() {
        if (bikeBuilder_ == null) {
          if (!(vehicleCase_ == 2)) {
            vehicle_ = VehicleOuterClass.Vehicle.Bike.getDefaultInstance();
          }
          bikeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              VehicleOuterClass.Vehicle.Bike, VehicleOuterClass.Vehicle.Bike.Builder, VehicleOuterClass.Vehicle.BikeOrBuilder>(
                  (VehicleOuterClass.Vehicle.Bike) vehicle_,
                  getParentForChildren(),
                  isClean());
          vehicle_ = null;
        }
        vehicleCase_ = 2;
        onChanged();
        return bikeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleOuterClass.Vehicle.Car, VehicleOuterClass.Vehicle.Car.Builder, VehicleOuterClass.Vehicle.CarOrBuilder> carBuilder_;
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       * @return Whether the car field is set.
       */
      @java.lang.Override
      public boolean hasCar() {
        return vehicleCase_ == 3;
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       * @return The car.
       */
      @java.lang.Override
      public VehicleOuterClass.Vehicle.Car getCar() {
        if (carBuilder_ == null) {
          if (vehicleCase_ == 3) {
            return (VehicleOuterClass.Vehicle.Car) vehicle_;
          }
          return VehicleOuterClass.Vehicle.Car.getDefaultInstance();
        } else {
          if (vehicleCase_ == 3) {
            return carBuilder_.getMessage();
          }
          return VehicleOuterClass.Vehicle.Car.getDefaultInstance();
        }
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      public Builder setCar(VehicleOuterClass.Vehicle.Car value) {
        if (carBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vehicle_ = value;
          onChanged();
        } else {
          carBuilder_.setMessage(value);
        }
        vehicleCase_ = 3;
        return this;
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      public Builder setCar(
          VehicleOuterClass.Vehicle.Car.Builder builderForValue) {
        if (carBuilder_ == null) {
          vehicle_ = builderForValue.build();
          onChanged();
        } else {
          carBuilder_.setMessage(builderForValue.build());
        }
        vehicleCase_ = 3;
        return this;
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      public Builder mergeCar(VehicleOuterClass.Vehicle.Car value) {
        if (carBuilder_ == null) {
          if (vehicleCase_ == 3 &&
              vehicle_ != VehicleOuterClass.Vehicle.Car.getDefaultInstance()) {
            vehicle_ = VehicleOuterClass.Vehicle.Car.newBuilder((VehicleOuterClass.Vehicle.Car) vehicle_)
                .mergeFrom(value).buildPartial();
          } else {
            vehicle_ = value;
          }
          onChanged();
        } else {
          if (vehicleCase_ == 3) {
            carBuilder_.mergeFrom(value);
          } else {
            carBuilder_.setMessage(value);
          }
        }
        vehicleCase_ = 3;
        return this;
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      public Builder clearCar() {
        if (carBuilder_ == null) {
          if (vehicleCase_ == 3) {
            vehicleCase_ = 0;
            vehicle_ = null;
            onChanged();
          }
        } else {
          if (vehicleCase_ == 3) {
            vehicleCase_ = 0;
            vehicle_ = null;
          }
          carBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      public VehicleOuterClass.Vehicle.Car.Builder getCarBuilder() {
        return getCarFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      @java.lang.Override
      public VehicleOuterClass.Vehicle.CarOrBuilder getCarOrBuilder() {
        if ((vehicleCase_ == 3) && (carBuilder_ != null)) {
          return carBuilder_.getMessageOrBuilder();
        } else {
          if (vehicleCase_ == 3) {
            return (VehicleOuterClass.Vehicle.Car) vehicle_;
          }
          return VehicleOuterClass.Vehicle.Car.getDefaultInstance();
        }
      }
      /**
       * <code>.Vehicle.Car Car = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleOuterClass.Vehicle.Car, VehicleOuterClass.Vehicle.Car.Builder, VehicleOuterClass.Vehicle.CarOrBuilder> 
          getCarFieldBuilder() {
        if (carBuilder_ == null) {
          if (!(vehicleCase_ == 3)) {
            vehicle_ = VehicleOuterClass.Vehicle.Car.getDefaultInstance();
          }
          carBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              VehicleOuterClass.Vehicle.Car, VehicleOuterClass.Vehicle.Car.Builder, VehicleOuterClass.Vehicle.CarOrBuilder>(
                  (VehicleOuterClass.Vehicle.Car) vehicle_,
                  getParentForChildren(),
                  isClean());
          vehicle_ = null;
        }
        vehicleCase_ = 3;
        onChanged();
        return carBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserOuterClass.User();
    }

    public static UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\032\rVehicle.proto\"[\n\004User\022\014\n\004n" +
      "ame\030\001 \001(\t\022\035\n\004Bike\030\002 \001(\0132\r.Vehicle.BikeH\000" +
      "\022\033\n\003Car\030\003 \001(\0132\014.Vehicle.CarH\000B\t\n\007vehicle" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          VehicleOuterClass.getDescriptor(),
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Name", "Bike", "Car", "Vehicle", });
    VehicleOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
