// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WithNestClassA.proto

public final class WithNestClassAOuterClass {
  private WithNestClassAOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WithNestClassAOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WithNestClassA)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     * @return The a.
     */
    WithNestClassAOuterClass.WithNestClassA.NestedClass getA();
    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     */
    WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder getAOrBuilder();
  }
  /**
   * Protobuf type {@code WithNestClassA}
   */
  public static final class WithNestClassA extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WithNestClassA)
      WithNestClassAOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WithNestClassA.newBuilder() to construct.
    private WithNestClassA(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithNestClassA() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WithNestClassA();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WithNestClassAOuterClass.internal_static_WithNestClassA_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WithNestClassAOuterClass.internal_static_WithNestClassA_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WithNestClassAOuterClass.WithNestClassA.class, WithNestClassAOuterClass.WithNestClassA.Builder.class);
    }

    public interface NestedClassOrBuilder extends
        // @@protoc_insertion_point(interface_extends:WithNestClassA.NestedClass)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string nested = 1;</code>
       * @return The nested.
       */
      java.lang.String getNested();
      /**
       * <code>string nested = 1;</code>
       * @return The bytes for nested.
       */
      com.google.protobuf.ByteString
          getNestedBytes();
    }
    /**
     * Protobuf type {@code WithNestClassA.NestedClass}
     */
    public static final class NestedClass extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WithNestClassA.NestedClass)
        NestedClassOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use NestedClass.newBuilder() to construct.
      private NestedClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private NestedClass() {
        nested_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new NestedClass();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WithNestClassAOuterClass.internal_static_WithNestClassA_NestedClass_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WithNestClassAOuterClass.internal_static_WithNestClassA_NestedClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WithNestClassAOuterClass.WithNestClassA.NestedClass.class, WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder.class);
      }

      public static final int NESTED_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object nested_ = "";
      /**
       * <code>string nested = 1;</code>
       * @return The nested.
       */
      @java.lang.Override
      public java.lang.String getNested() {
        java.lang.Object ref = nested_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nested_ = s;
          return s;
        }
      }
      /**
       * <code>string nested = 1;</code>
       * @return The bytes for nested.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNestedBytes() {
        java.lang.Object ref = nested_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nested_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nested_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nested_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nested_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nested_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof WithNestClassAOuterClass.WithNestClassA.NestedClass)) {
          return super.equals(obj);
        }
        WithNestClassAOuterClass.WithNestClassA.NestedClass other = (WithNestClassAOuterClass.WithNestClassA.NestedClass) obj;

        if (!getNested()
            .equals(other.getNested())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NESTED_FIELD_NUMBER;
        hash = (53 * hash) + getNested().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static WithNestClassAOuterClass.WithNestClassA.NestedClass parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(WithNestClassAOuterClass.WithNestClassA.NestedClass prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code WithNestClassA.NestedClass}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:WithNestClassA.NestedClass)
          WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return WithNestClassAOuterClass.internal_static_WithNestClassA_NestedClass_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return WithNestClassAOuterClass.internal_static_WithNestClassA_NestedClass_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  WithNestClassAOuterClass.WithNestClassA.NestedClass.class, WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder.class);
        }

        // Construct using WithNestClassAOuterClass.WithNestClassA.NestedClass.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          nested_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return WithNestClassAOuterClass.internal_static_WithNestClassA_NestedClass_descriptor;
        }

        @java.lang.Override
        public WithNestClassAOuterClass.WithNestClassA.NestedClass getDefaultInstanceForType() {
          return WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance();
        }

        @java.lang.Override
        public WithNestClassAOuterClass.WithNestClassA.NestedClass build() {
          WithNestClassAOuterClass.WithNestClassA.NestedClass result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public WithNestClassAOuterClass.WithNestClassA.NestedClass buildPartial() {
          WithNestClassAOuterClass.WithNestClassA.NestedClass result = new WithNestClassAOuterClass.WithNestClassA.NestedClass(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(WithNestClassAOuterClass.WithNestClassA.NestedClass result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.nested_ = nested_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof WithNestClassAOuterClass.WithNestClassA.NestedClass) {
            return mergeFrom((WithNestClassAOuterClass.WithNestClassA.NestedClass)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(WithNestClassAOuterClass.WithNestClassA.NestedClass other) {
          if (other == WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance()) return this;
          if (!other.getNested().isEmpty()) {
            nested_ = other.nested_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  nested_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object nested_ = "";
        /**
         * <code>string nested = 1;</code>
         * @return The nested.
         */
        public java.lang.String getNested() {
          java.lang.Object ref = nested_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            nested_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string nested = 1;</code>
         * @return The bytes for nested.
         */
        public com.google.protobuf.ByteString
            getNestedBytes() {
          java.lang.Object ref = nested_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            nested_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string nested = 1;</code>
         * @param value The nested to set.
         * @return This builder for chaining.
         */
        public Builder setNested(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          nested_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string nested = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNested() {
          nested_ = getDefaultInstance().getNested();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string nested = 1;</code>
         * @param value The bytes for nested to set.
         * @return This builder for chaining.
         */
        public Builder setNestedBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          nested_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:WithNestClassA.NestedClass)
      }

      // @@protoc_insertion_point(class_scope:WithNestClassA.NestedClass)
      private static final WithNestClassAOuterClass.WithNestClassA.NestedClass DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new WithNestClassAOuterClass.WithNestClassA.NestedClass();
      }

      public static WithNestClassAOuterClass.WithNestClassA.NestedClass getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<NestedClass>
          PARSER = new com.google.protobuf.AbstractParser<NestedClass>() {
        @java.lang.Override
        public NestedClass parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<NestedClass> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<NestedClass> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public WithNestClassAOuterClass.WithNestClassA.NestedClass getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int A_FIELD_NUMBER = 1;
    private WithNestClassAOuterClass.WithNestClassA.NestedClass a_;
    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return a_ != null;
    }
    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public WithNestClassAOuterClass.WithNestClassA.NestedClass getA() {
      return a_ == null ? WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance() : a_;
    }
    /**
     * <code>.WithNestClassA.NestedClass a = 1;</code>
     */
    @java.lang.Override
    public WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder getAOrBuilder() {
      return a_ == null ? WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance() : a_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != null) {
        output.writeMessage(1, getA());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getA());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WithNestClassAOuterClass.WithNestClassA)) {
        return super.equals(obj);
      }
      WithNestClassAOuterClass.WithNestClassA other = (WithNestClassAOuterClass.WithNestClassA) obj;

      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (!getA()
            .equals(other.getA())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static WithNestClassAOuterClass.WithNestClassA parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static WithNestClassAOuterClass.WithNestClassA parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestClassAOuterClass.WithNestClassA parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WithNestClassAOuterClass.WithNestClassA prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WithNestClassA}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WithNestClassA)
        WithNestClassAOuterClass.WithNestClassAOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WithNestClassAOuterClass.internal_static_WithNestClassA_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WithNestClassAOuterClass.internal_static_WithNestClassA_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WithNestClassAOuterClass.WithNestClassA.class, WithNestClassAOuterClass.WithNestClassA.Builder.class);
      }

      // Construct using WithNestClassAOuterClass.WithNestClassA.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = null;
        if (aBuilder_ != null) {
          aBuilder_.dispose();
          aBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WithNestClassAOuterClass.internal_static_WithNestClassA_descriptor;
      }

      @java.lang.Override
      public WithNestClassAOuterClass.WithNestClassA getDefaultInstanceForType() {
        return WithNestClassAOuterClass.WithNestClassA.getDefaultInstance();
      }

      @java.lang.Override
      public WithNestClassAOuterClass.WithNestClassA build() {
        WithNestClassAOuterClass.WithNestClassA result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public WithNestClassAOuterClass.WithNestClassA buildPartial() {
        WithNestClassAOuterClass.WithNestClassA result = new WithNestClassAOuterClass.WithNestClassA(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(WithNestClassAOuterClass.WithNestClassA result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = aBuilder_ == null
              ? a_
              : aBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WithNestClassAOuterClass.WithNestClassA) {
          return mergeFrom((WithNestClassAOuterClass.WithNestClassA)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WithNestClassAOuterClass.WithNestClassA other) {
        if (other == WithNestClassAOuterClass.WithNestClassA.getDefaultInstance()) return this;
        if (other.hasA()) {
          mergeA(other.getA());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private WithNestClassAOuterClass.WithNestClassA.NestedClass a_;
      private com.google.protobuf.SingleFieldBuilderV3<
          WithNestClassAOuterClass.WithNestClassA.NestedClass, WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder, WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder> aBuilder_;
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       * @return Whether the a field is set.
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       * @return The a.
       */
      public WithNestClassAOuterClass.WithNestClassA.NestedClass getA() {
        if (aBuilder_ == null) {
          return a_ == null ? WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance() : a_;
        } else {
          return aBuilder_.getMessage();
        }
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public Builder setA(WithNestClassAOuterClass.WithNestClassA.NestedClass value) {
        if (aBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          a_ = value;
        } else {
          aBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public Builder setA(
          WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder builderForValue) {
        if (aBuilder_ == null) {
          a_ = builderForValue.build();
        } else {
          aBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public Builder mergeA(WithNestClassAOuterClass.WithNestClassA.NestedClass value) {
        if (aBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            a_ != null &&
            a_ != WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance()) {
            getABuilder().mergeFrom(value);
          } else {
            a_ = value;
          }
        } else {
          aBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = null;
        if (aBuilder_ != null) {
          aBuilder_.dispose();
          aBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder getABuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAFieldBuilder().getBuilder();
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      public WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder getAOrBuilder() {
        if (aBuilder_ != null) {
          return aBuilder_.getMessageOrBuilder();
        } else {
          return a_ == null ?
              WithNestClassAOuterClass.WithNestClassA.NestedClass.getDefaultInstance() : a_;
        }
      }
      /**
       * <code>.WithNestClassA.NestedClass a = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          WithNestClassAOuterClass.WithNestClassA.NestedClass, WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder, WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder> 
          getAFieldBuilder() {
        if (aBuilder_ == null) {
          aBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              WithNestClassAOuterClass.WithNestClassA.NestedClass, WithNestClassAOuterClass.WithNestClassA.NestedClass.Builder, WithNestClassAOuterClass.WithNestClassA.NestedClassOrBuilder>(
                  getA(),
                  getParentForChildren(),
                  isClean());
          a_ = null;
        }
        return aBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WithNestClassA)
    }

    // @@protoc_insertion_point(class_scope:WithNestClassA)
    private static final WithNestClassAOuterClass.WithNestClassA DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WithNestClassAOuterClass.WithNestClassA();
    }

    public static WithNestClassAOuterClass.WithNestClassA getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WithNestClassA>
        PARSER = new com.google.protobuf.AbstractParser<WithNestClassA>() {
      @java.lang.Override
      public WithNestClassA parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WithNestClassA> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithNestClassA> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public WithNestClassAOuterClass.WithNestClassA getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithNestClassA_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithNestClassA_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithNestClassA_NestedClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithNestClassA_NestedClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WithNestClassA.proto\"W\n\016WithNestClassA" +
      "\022&\n\001a\030\001 \001(\0132\033.WithNestClassA.NestedClass" +
      "\032\035\n\013NestedClass\022\016\n\006nested\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WithNestClassA_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WithNestClassA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithNestClassA_descriptor,
        new java.lang.String[] { "A", });
    internal_static_WithNestClassA_NestedClass_descriptor =
      internal_static_WithNestClassA_descriptor.getNestedTypes().get(0);
    internal_static_WithNestClassA_NestedClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithNestClassA_NestedClass_descriptor,
        new java.lang.String[] { "Nested", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
