// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WithNestedEnum.proto

public final class WithNestedEnumOuterClass {
  private WithNestedEnumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WithNestedEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WithNestedEnum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
     * @return The enum numeric value on the wire for enum.
     */
    int getEnumValue();
    /**
     * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
     * @return The enum.
     */
    WithNestedEnumOuterClass.WithNestedEnum.NestedEnum getEnum();
  }
  /**
   * Protobuf type {@code WithNestedEnum}
   */
  public static final class WithNestedEnum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WithNestedEnum)
      WithNestedEnumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WithNestedEnum.newBuilder() to construct.
    private WithNestedEnum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithNestedEnum() {
      enum_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WithNestedEnum();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WithNestedEnumOuterClass.internal_static_WithNestedEnum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WithNestedEnumOuterClass.internal_static_WithNestedEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WithNestedEnumOuterClass.WithNestedEnum.class, WithNestedEnumOuterClass.WithNestedEnum.Builder.class);
    }

    /**
     * Protobuf enum {@code WithNestedEnum.NestedEnum}
     */
    public enum NestedEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>A = 0;</code>
       */
      A(0),
      /**
       * <code>B = 1;</code>
       */
      B(1),
      /**
       * <code>C = 2;</code>
       */
      C(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>A = 0;</code>
       */
      public static final int A_VALUE = 0;
      /**
       * <code>B = 1;</code>
       */
      public static final int B_VALUE = 1;
      /**
       * <code>C = 2;</code>
       */
      public static final int C_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NestedEnum valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NestedEnum forNumber(int value) {
        switch (value) {
          case 0: return A;
          case 1: return B;
          case 2: return C;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NestedEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NestedEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NestedEnum>() {
              public NestedEnum findValueByNumber(int number) {
                return NestedEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return WithNestedEnumOuterClass.WithNestedEnum.getDescriptor().getEnumTypes().get(0);
      }

      private static final NestedEnum[] VALUES = values();

      public static NestedEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NestedEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WithNestedEnum.NestedEnum)
    }

    public static final int ENUM_FIELD_NUMBER = 1;
    private int enum_ = 0;
    /**
     * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
     * @return The enum numeric value on the wire for enum.
     */
    @java.lang.Override public int getEnumValue() {
      return enum_;
    }
    /**
     * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
     * @return The enum.
     */
    @java.lang.Override public WithNestedEnumOuterClass.WithNestedEnum.NestedEnum getEnum() {
      WithNestedEnumOuterClass.WithNestedEnum.NestedEnum result = WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.forNumber(enum_);
      return result == null ? WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enum_ != WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.A.getNumber()) {
        output.writeEnum(1, enum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enum_ != WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.A.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, enum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WithNestedEnumOuterClass.WithNestedEnum)) {
        return super.equals(obj);
      }
      WithNestedEnumOuterClass.WithNestedEnum other = (WithNestedEnumOuterClass.WithNestedEnum) obj;

      if (enum_ != other.enum_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENUM_FIELD_NUMBER;
      hash = (53 * hash) + enum_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static WithNestedEnumOuterClass.WithNestedEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static WithNestedEnumOuterClass.WithNestedEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestedEnumOuterClass.WithNestedEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WithNestedEnumOuterClass.WithNestedEnum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WithNestedEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WithNestedEnum)
        WithNestedEnumOuterClass.WithNestedEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WithNestedEnumOuterClass.internal_static_WithNestedEnum_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WithNestedEnumOuterClass.internal_static_WithNestedEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WithNestedEnumOuterClass.WithNestedEnum.class, WithNestedEnumOuterClass.WithNestedEnum.Builder.class);
      }

      // Construct using WithNestedEnumOuterClass.WithNestedEnum.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enum_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WithNestedEnumOuterClass.internal_static_WithNestedEnum_descriptor;
      }

      @java.lang.Override
      public WithNestedEnumOuterClass.WithNestedEnum getDefaultInstanceForType() {
        return WithNestedEnumOuterClass.WithNestedEnum.getDefaultInstance();
      }

      @java.lang.Override
      public WithNestedEnumOuterClass.WithNestedEnum build() {
        WithNestedEnumOuterClass.WithNestedEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public WithNestedEnumOuterClass.WithNestedEnum buildPartial() {
        WithNestedEnumOuterClass.WithNestedEnum result = new WithNestedEnumOuterClass.WithNestedEnum(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(WithNestedEnumOuterClass.WithNestedEnum result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enum_ = enum_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WithNestedEnumOuterClass.WithNestedEnum) {
          return mergeFrom((WithNestedEnumOuterClass.WithNestedEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WithNestedEnumOuterClass.WithNestedEnum other) {
        if (other == WithNestedEnumOuterClass.WithNestedEnum.getDefaultInstance()) return this;
        if (other.enum_ != 0) {
          setEnumValue(other.getEnumValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                enum_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int enum_ = 0;
      /**
       * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
       * @return The enum numeric value on the wire for enum.
       */
      @java.lang.Override public int getEnumValue() {
        return enum_;
      }
      /**
       * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
       * @param value The enum numeric value on the wire for enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnumValue(int value) {
        enum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
       * @return The enum.
       */
      @java.lang.Override
      public WithNestedEnumOuterClass.WithNestedEnum.NestedEnum getEnum() {
        WithNestedEnumOuterClass.WithNestedEnum.NestedEnum result = WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.forNumber(enum_);
        return result == null ? WithNestedEnumOuterClass.WithNestedEnum.NestedEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
       * @param value The enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnum(WithNestedEnumOuterClass.WithNestedEnum.NestedEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        enum_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestedEnum.NestedEnum enum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WithNestedEnum)
    }

    // @@protoc_insertion_point(class_scope:WithNestedEnum)
    private static final WithNestedEnumOuterClass.WithNestedEnum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WithNestedEnumOuterClass.WithNestedEnum();
    }

    public static WithNestedEnumOuterClass.WithNestedEnum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WithNestedEnum>
        PARSER = new com.google.protobuf.AbstractParser<WithNestedEnum>() {
      @java.lang.Override
      public WithNestedEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WithNestedEnum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithNestedEnum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public WithNestedEnumOuterClass.WithNestedEnum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithNestedEnum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithNestedEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WithNestedEnum.proto\"]\n\016WithNestedEnum" +
      "\022(\n\004enum\030\001 \001(\0162\032.WithNestedEnum.NestedEn" +
      "um\"!\n\nNestedEnum\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\002b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WithNestedEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WithNestedEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithNestedEnum_descriptor,
        new java.lang.String[] { "Enum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
