// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WithNestClassB.proto

public final class WithNestClassBOuterClass {
  private WithNestClassBOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WithNestClassBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WithNestClassB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     * @return The b.
     */
    WithNestClassBOuterClass.WithNestClassB.NestedClass getB();
    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     */
    WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder getBOrBuilder();
  }
  /**
   * Protobuf type {@code WithNestClassB}
   */
  public static final class WithNestClassB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WithNestClassB)
      WithNestClassBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WithNestClassB.newBuilder() to construct.
    private WithNestClassB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithNestClassB() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WithNestClassB();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WithNestClassBOuterClass.internal_static_WithNestClassB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WithNestClassBOuterClass.internal_static_WithNestClassB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WithNestClassBOuterClass.WithNestClassB.class, WithNestClassBOuterClass.WithNestClassB.Builder.class);
    }

    public interface NestedClassOrBuilder extends
        // @@protoc_insertion_point(interface_extends:WithNestClassB.NestedClass)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
       * @return The enum numeric value on the wire for nestedEnum.
       */
      int getNestedEnumValue();
      /**
       * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
       * @return The nestedEnum.
       */
      WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum getNestedEnum();
    }
    /**
     * Protobuf type {@code WithNestClassB.NestedClass}
     */
    public static final class NestedClass extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WithNestClassB.NestedClass)
        NestedClassOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use NestedClass.newBuilder() to construct.
      private NestedClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private NestedClass() {
        nestedEnum_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new NestedClass();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WithNestClassBOuterClass.internal_static_WithNestClassB_NestedClass_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WithNestClassBOuterClass.internal_static_WithNestClassB_NestedClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WithNestClassBOuterClass.WithNestClassB.NestedClass.class, WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder.class);
      }

      /**
       * Protobuf enum {@code WithNestClassB.NestedClass.NestedEnum}
       */
      public enum NestedEnum
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>A = 0;</code>
         */
        A(0),
        /**
         * <code>B = 1;</code>
         */
        B(1),
        /**
         * <code>C = 2;</code>
         */
        C(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>A = 0;</code>
         */
        public static final int A_VALUE = 0;
        /**
         * <code>B = 1;</code>
         */
        public static final int B_VALUE = 1;
        /**
         * <code>C = 2;</code>
         */
        public static final int C_VALUE = 2;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static NestedEnum valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static NestedEnum forNumber(int value) {
          switch (value) {
            case 0: return A;
            case 1: return B;
            case 2: return C;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<NestedEnum>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            NestedEnum> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<NestedEnum>() {
                public NestedEnum findValueByNumber(int number) {
                  return NestedEnum.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return WithNestClassBOuterClass.WithNestClassB.NestedClass.getDescriptor().getEnumTypes().get(0);
        }

        private static final NestedEnum[] VALUES = values();

        public static NestedEnum valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private NestedEnum(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:WithNestClassB.NestedClass.NestedEnum)
      }

      public static final int NESTEDENUM_FIELD_NUMBER = 1;
      private int nestedEnum_ = 0;
      /**
       * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
       * @return The enum numeric value on the wire for nestedEnum.
       */
      @java.lang.Override public int getNestedEnumValue() {
        return nestedEnum_;
      }
      /**
       * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
       * @return The nestedEnum.
       */
      @java.lang.Override public WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum getNestedEnum() {
        WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum result = WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.forNumber(nestedEnum_);
        return result == null ? WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (nestedEnum_ != WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.A.getNumber()) {
          output.writeEnum(1, nestedEnum_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (nestedEnum_ != WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.A.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, nestedEnum_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof WithNestClassBOuterClass.WithNestClassB.NestedClass)) {
          return super.equals(obj);
        }
        WithNestClassBOuterClass.WithNestClassB.NestedClass other = (WithNestClassBOuterClass.WithNestClassB.NestedClass) obj;

        if (nestedEnum_ != other.nestedEnum_) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NESTEDENUM_FIELD_NUMBER;
        hash = (53 * hash) + nestedEnum_;
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static WithNestClassBOuterClass.WithNestClassB.NestedClass parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(WithNestClassBOuterClass.WithNestClassB.NestedClass prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code WithNestClassB.NestedClass}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:WithNestClassB.NestedClass)
          WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return WithNestClassBOuterClass.internal_static_WithNestClassB_NestedClass_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return WithNestClassBOuterClass.internal_static_WithNestClassB_NestedClass_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  WithNestClassBOuterClass.WithNestClassB.NestedClass.class, WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder.class);
        }

        // Construct using WithNestClassBOuterClass.WithNestClassB.NestedClass.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          nestedEnum_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return WithNestClassBOuterClass.internal_static_WithNestClassB_NestedClass_descriptor;
        }

        @java.lang.Override
        public WithNestClassBOuterClass.WithNestClassB.NestedClass getDefaultInstanceForType() {
          return WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance();
        }

        @java.lang.Override
        public WithNestClassBOuterClass.WithNestClassB.NestedClass build() {
          WithNestClassBOuterClass.WithNestClassB.NestedClass result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public WithNestClassBOuterClass.WithNestClassB.NestedClass buildPartial() {
          WithNestClassBOuterClass.WithNestClassB.NestedClass result = new WithNestClassBOuterClass.WithNestClassB.NestedClass(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(WithNestClassBOuterClass.WithNestClassB.NestedClass result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.nestedEnum_ = nestedEnum_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof WithNestClassBOuterClass.WithNestClassB.NestedClass) {
            return mergeFrom((WithNestClassBOuterClass.WithNestClassB.NestedClass)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(WithNestClassBOuterClass.WithNestClassB.NestedClass other) {
          if (other == WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance()) return this;
          if (other.nestedEnum_ != 0) {
            setNestedEnumValue(other.getNestedEnumValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  nestedEnum_ = input.readEnum();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int nestedEnum_ = 0;
        /**
         * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
         * @return The enum numeric value on the wire for nestedEnum.
         */
        @java.lang.Override public int getNestedEnumValue() {
          return nestedEnum_;
        }
        /**
         * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
         * @param value The enum numeric value on the wire for nestedEnum to set.
         * @return This builder for chaining.
         */
        public Builder setNestedEnumValue(int value) {
          nestedEnum_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
         * @return The nestedEnum.
         */
        @java.lang.Override
        public WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum getNestedEnum() {
          WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum result = WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.forNumber(nestedEnum_);
          return result == null ? WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum.UNRECOGNIZED : result;
        }
        /**
         * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
         * @param value The nestedEnum to set.
         * @return This builder for chaining.
         */
        public Builder setNestedEnum(WithNestClassBOuterClass.WithNestClassB.NestedClass.NestedEnum value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          nestedEnum_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.WithNestClassB.NestedClass.NestedEnum nestedEnum = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNestedEnum() {
          bitField0_ = (bitField0_ & ~0x00000001);
          nestedEnum_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:WithNestClassB.NestedClass)
      }

      // @@protoc_insertion_point(class_scope:WithNestClassB.NestedClass)
      private static final WithNestClassBOuterClass.WithNestClassB.NestedClass DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new WithNestClassBOuterClass.WithNestClassB.NestedClass();
      }

      public static WithNestClassBOuterClass.WithNestClassB.NestedClass getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<NestedClass>
          PARSER = new com.google.protobuf.AbstractParser<NestedClass>() {
        @java.lang.Override
        public NestedClass parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<NestedClass> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<NestedClass> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public WithNestClassBOuterClass.WithNestClassB.NestedClass getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int B_FIELD_NUMBER = 1;
    private WithNestClassBOuterClass.WithNestClassB.NestedClass b_;
    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return b_ != null;
    }
    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     * @return The b.
     */
    @java.lang.Override
    public WithNestClassBOuterClass.WithNestClassB.NestedClass getB() {
      return b_ == null ? WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance() : b_;
    }
    /**
     * <code>.WithNestClassB.NestedClass b = 1;</code>
     */
    @java.lang.Override
    public WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder getBOrBuilder() {
      return b_ == null ? WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance() : b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (b_ != null) {
        output.writeMessage(1, getB());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (b_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getB());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WithNestClassBOuterClass.WithNestClassB)) {
        return super.equals(obj);
      }
      WithNestClassBOuterClass.WithNestClassB other = (WithNestClassBOuterClass.WithNestClassB) obj;

      if (hasB() != other.hasB()) return false;
      if (hasB()) {
        if (!getB()
            .equals(other.getB())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static WithNestClassBOuterClass.WithNestClassB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static WithNestClassBOuterClass.WithNestClassB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WithNestClassBOuterClass.WithNestClassB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WithNestClassBOuterClass.WithNestClassB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WithNestClassB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WithNestClassB)
        WithNestClassBOuterClass.WithNestClassBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WithNestClassBOuterClass.internal_static_WithNestClassB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WithNestClassBOuterClass.internal_static_WithNestClassB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WithNestClassBOuterClass.WithNestClassB.class, WithNestClassBOuterClass.WithNestClassB.Builder.class);
      }

      // Construct using WithNestClassBOuterClass.WithNestClassB.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        b_ = null;
        if (bBuilder_ != null) {
          bBuilder_.dispose();
          bBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WithNestClassBOuterClass.internal_static_WithNestClassB_descriptor;
      }

      @java.lang.Override
      public WithNestClassBOuterClass.WithNestClassB getDefaultInstanceForType() {
        return WithNestClassBOuterClass.WithNestClassB.getDefaultInstance();
      }

      @java.lang.Override
      public WithNestClassBOuterClass.WithNestClassB build() {
        WithNestClassBOuterClass.WithNestClassB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public WithNestClassBOuterClass.WithNestClassB buildPartial() {
        WithNestClassBOuterClass.WithNestClassB result = new WithNestClassBOuterClass.WithNestClassB(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(WithNestClassBOuterClass.WithNestClassB result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.b_ = bBuilder_ == null
              ? b_
              : bBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WithNestClassBOuterClass.WithNestClassB) {
          return mergeFrom((WithNestClassBOuterClass.WithNestClassB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WithNestClassBOuterClass.WithNestClassB other) {
        if (other == WithNestClassBOuterClass.WithNestClassB.getDefaultInstance()) return this;
        if (other.hasB()) {
          mergeB(other.getB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getBFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private WithNestClassBOuterClass.WithNestClassB.NestedClass b_;
      private com.google.protobuf.SingleFieldBuilderV3<
          WithNestClassBOuterClass.WithNestClassB.NestedClass, WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder, WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder> bBuilder_;
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       * @return The b.
       */
      public WithNestClassBOuterClass.WithNestClassB.NestedClass getB() {
        if (bBuilder_ == null) {
          return b_ == null ? WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance() : b_;
        } else {
          return bBuilder_.getMessage();
        }
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public Builder setB(WithNestClassBOuterClass.WithNestClassB.NestedClass value) {
        if (bBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b_ = value;
        } else {
          bBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public Builder setB(
          WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder builderForValue) {
        if (bBuilder_ == null) {
          b_ = builderForValue.build();
        } else {
          bBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public Builder mergeB(WithNestClassBOuterClass.WithNestClassB.NestedClass value) {
        if (bBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            b_ != null &&
            b_ != WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance()) {
            getBBuilder().mergeFrom(value);
          } else {
            b_ = value;
          }
        } else {
          bBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000001);
        b_ = null;
        if (bBuilder_ != null) {
          bBuilder_.dispose();
          bBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder getBBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBFieldBuilder().getBuilder();
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      public WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder getBOrBuilder() {
        if (bBuilder_ != null) {
          return bBuilder_.getMessageOrBuilder();
        } else {
          return b_ == null ?
              WithNestClassBOuterClass.WithNestClassB.NestedClass.getDefaultInstance() : b_;
        }
      }
      /**
       * <code>.WithNestClassB.NestedClass b = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          WithNestClassBOuterClass.WithNestClassB.NestedClass, WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder, WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder> 
          getBFieldBuilder() {
        if (bBuilder_ == null) {
          bBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              WithNestClassBOuterClass.WithNestClassB.NestedClass, WithNestClassBOuterClass.WithNestClassB.NestedClass.Builder, WithNestClassBOuterClass.WithNestClassB.NestedClassOrBuilder>(
                  getB(),
                  getParentForChildren(),
                  isClean());
          b_ = null;
        }
        return bBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WithNestClassB)
    }

    // @@protoc_insertion_point(class_scope:WithNestClassB)
    private static final WithNestClassBOuterClass.WithNestClassB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WithNestClassBOuterClass.WithNestClassB();
    }

    public static WithNestClassBOuterClass.WithNestClassB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WithNestClassB>
        PARSER = new com.google.protobuf.AbstractParser<WithNestClassB>() {
      @java.lang.Override
      public WithNestClassB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WithNestClassB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithNestClassB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public WithNestClassBOuterClass.WithNestClassB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithNestClassB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithNestClassB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithNestClassB_NestedClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithNestClassB_NestedClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WithNestClassB.proto\"\246\001\n\016WithNestClass" +
      "B\022&\n\001b\030\001 \001(\0132\033.WithNestClassB.NestedClas" +
      "s\032l\n\013NestedClass\022:\n\nnestedEnum\030\001 \001(\0162&.W" +
      "ithNestClassB.NestedClass.NestedEnum\"!\n\n" +
      "NestedEnum\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WithNestClassB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WithNestClassB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithNestClassB_descriptor,
        new java.lang.String[] { "B", });
    internal_static_WithNestClassB_NestedClass_descriptor =
      internal_static_WithNestClassB_descriptor.getNestedTypes().get(0);
    internal_static_WithNestClassB_NestedClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithNestClassB_NestedClass_descriptor,
        new java.lang.String[] { "NestedEnum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
